### PR TITLE
Add support for transform types

### LINKED ISSUE #125: Support for transform types
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the feature has not already been requested

### 🚀 Feature Proposal

Now that TypeBox supports [transform types](https://github.com/sinclairzx81/typebox/blob/master/changelog/0.30.0.md), it would be great if this library supported them as well.

### Example

I made a branch that should work here: https://github.com/fastify/fastify-type-provider-typebox/compare/main...ehaynes99:fastify-type-provider-typebox:transform-types

However, this lib currently allows TypeBox versions down to 0.26, and transform types were only added in 0.30. I could work around it for the actual conversion like [here](https://github.com/ehaynes99/fastify-type-provider-typebox/blob/4a303c3387898aa83418dbb001e337a3f40bc813/index.mts#L32):

```typescript
// Decode added in TypeBox 0.30
const decoded = ('Decode' in Value) ? Value.Decode(schema, converted) : converted
```
but there's not a way to fix the types, because `StaticDecode` would not exist in those older versions. In order to merge this, the compatible version range would have to be updated.

```diff
diff --git a/package.json b/package.json
index e6af223..783bda7 100644
--- a/package.json
+++ b/package.json
@@ -18,7 +18,7 @@
     }
   },
   "peerDependencies": {
-    "@sinclair/typebox": ">=0.26 <=0.32"
+    "@sinclair/typebox": ">=0.30 <=0.32"
   },
   "scripts": {
     "build:clean": "rimraf ./dist",
```

### PR DESCRIPTION
**Pull request by ehaynes99**
fixes #125
#### Checklist

- [ ] run `npm run test` and `npm run benchmark` (tests pass, but no `benchmark` script exists)
- [x] tests and/or benchmarks are included
- [ ] documentation is changed or added (I don't think this needs an update)
- [x] commit message and code follows the [Developer's Certification of Origin](https://github.com/fastify/.github/blob/master/CONTRIBUTING.md#developers-certificate-of-origin-11)
      and the [Code of conduct](https://github.com/fastify/.github/blob/master/CODE_OF_CONDUCT.md)

### CODE REVIEW

**Comment by mcollina** [comment]
Could you adjust the versions in CI?

**Comment by ehaynes99** [comment]
> Could you adjust the versions in CI?

Ah, sorry, didn't know that existed.

**Review by mcollina — COMMENTED** [review]
What would happen if a TransformType is used with the stock validator compiler?

**Comment by ehaynes99** [comment]
> What would happen if a TransformType is used with the stock validator compiler?

Hrmm, yeah, I guess that won't work. Honestly I've just always used these together. I guess that means that this would need two independent type providers, e.g. `TypeBoxTypeProvider` and `TypeBoxTransformTypeProvider`, and require the user to pick based on whether the validator compiler is used or not.

Regarding the tests, I'll try to track down which specific version had `StaticDecode`. I _thought_ it was in 0.30.0 based on the changelog, but apparently not.
https://github.com/sinclairzx81/typebox/blob/master/changelog/0.30.0.md

I'll close this for now and try to come up with something else. It'll probably be a few days before I can get back to it though.

**Comment by tothdanielax** [comment]
@ehaynes99, followed your setup as it is super handy for our scenario. But it seems the conversion works only for query, params and headers. Is there a way to decode the body also (I receive ids represented as strings and it's needed to be converted to Mongo ObjectIds)?

**Comment by ehaynes99** [comment]
@tothdanielax Hrmm, I'm not sure how that's possible. The test I added for `'should decode transform types'` actually only tests the body conversion, not query or path, so if anything wasn't working, I would expect it to be one of the others.

The TypeBox author added a PR for this a while ago, but ended up closing it because of the version range issue. That's probably a better way forward because it handles the case @mcollina mentions as it precludes the combination of transform types without transforms in the validator compiler.

Sorry, I've been pretty swamped, but I'll try to resurrect that one instead. 
See:
https://github.com/sinclairzx81/typebox/issues/343#issuecomment-1937101432

I think the syntax can easily be adapted to have flags for the other two new options (though i guess that would prompt an even narrower version range, so we could add it separately).

Using the same parameter names from ajv, that could look something like:
```typescript
const fastify = TypeBoxTransformProvider(Fastify(), {
  removeAdditional: true,
  useDefaults: true,
})
```

**Pull request closed without merging**
