### PR TITLE
chore: update fastify to ^5.0.0

### PR DESCRIPTION
**Pull request by Fdawgs**
See  https://github.com/fastify/fastify/issues/5694

#### Checklist

- [x] run `npm run test` and `npm run benchmark`
- [x] commit message and code follows the [Developer's Certification of Origin](https://github.com/fastify/.github/blob/master/CONTRIBUTING.md#developers-certificate-of-origin-11)
      and the [Code of conduct](https://github.com/fastify/.github/blob/master/CODE_OF_CONDUCT.md)

### CODE REVIEW

**Comment by mcollina** [comment]
@Fdawgs can you take a look at why this is failing?

**Comment by Fdawgs** [comment]
Issue is that the `dist/cjs/index.js` file built when running `build:cjs` has ESM Module import syntax in it:

```js
"use strict";
import { TypeCompiler } from '@sinclair/typebox/compiler';
import { Value } from '@sinclair/typebox/value';
export * from '@sinclair/typebox';
export const TypeBoxValidatorCompiler = ({ schema, httpPart }) => {
    const typeCheck = TypeCompiler.Compile(schema);
    return (value) => {
        const converted = httpPart === 'body' ? value : Value.Convert(schema, value);
        if (typeCheck.Check(converted)) {
            return { value: converted };
        }
        const errors = [...typeCheck.Errors(converted)];
        return {
            error: errors.map((error) => ({
                message: `${error.message}`,
                instancePath: error.path
            }))
        };
    };
};
```

The build tools haven't changed since the last succesful release: https://github.com/fastify/fastify-type-provider-typebox/actions/runs/10698067891/job/29656641884

Still TypeScript 5.4.5 >:(

**Comment by Fdawgs** [comment]
Yep, if i pin typescript to 5.4.5 instead of `^5.4.5` then it's fine.

image

**Comment by climba03003** [comment]
I recommend always use `~` for TypeScript since TypeScript use `x.y` as major version and `.z` for patch.

**Pull request merged**
