### PR TITLE
chore: update TypeBox highest version

### LINKED ISSUE #161: Update TypeBox to 0.33.4
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the issue has not already been raised

### Issue

I'm getting a peer-dep issue:
```
npm error Could not resolve dependency:
npm error peer @sinclair/typebox@">=0.26 <=0.32" from @fastify/type-provider-typebox@4.0.0
npm error node_modules/@fastify/type-provider-typebox
npm error   @fastify/type-provider-typebox@"^4.0.0" from the root project
```

Don't know wether there are breaking changes. Is this open for contribution?

### PR DESCRIPTION
**Pull request by nickfla1**
Fixes #161

Updates the highest TypeBox version to <= 0.33.x

#### Checklist

- [x] run `npm run test` and `npm run benchmark`
- [x] tests and/or benchmarks are included
- [ ] documentation is changed or added
- [x] commit message and code follows the [Developer's Certification of Origin](https://github.com/fastify/.github/blob/master/CONTRIBUTING.md#developers-certificate-of-origin-11)
      and the [Code of conduct](https://github.com/fastify/.github/blob/master/CODE_OF_CONDUCT.md)

### CODE REVIEW

**Review by gurgunday — COMMENTED** [review]
CI is failing

**Comment by nickfla1** [comment]
The CI fails with

> Attempting to download 14...
Not found in manifest. Falling back to download directly from Node
Error: Unable to find Node version '14' for platform darwin and architecture arm64.

I don't think it's related to this PR. Is still supporting node 14 a requirement for this package?

**Comment by gurgunday** [comment]
Oh, I thought you were targeting main

This issue is about node 14 (and 16?) on macos

We should exclude them from the workflow

**Comment by nickfla1** [comment]
> Oh, I thought you were targeting main

I targeted the current active version, I thought then we could forward port it. Let me know if you prefer the other way around, I'll rebase!

> We should exclude them from the workflow

Shall I do it in this PR? I can open a new on to fix this problem first

**Comment by gurgunday** [comment]
> Shall I do it in this PR? I can open a new on to fix this problem first

Please! A new PR to `v4` branch like this one would be appreciated

You can see an example here of the exclusions I'm talking about: https://github.com/fastify/workflows/blob/28dd54c988abaceeb5df90ab1d7e21ad30a96e92/.github/workflows/plugins-ci.yml#L108-L114

> I targeted the current active version, I thought then we could forward port it. Let me know if you prefer the other way around, I'll rebase!

It's not crucial but backporting can be more straightforward with `git cherry-pick`

**Comment by nickfla1** [comment]
> Please! A new PR to `v4` branch like this one would be appreciated

Fixed in https://github.com/fastify/fastify-type-provider-typebox/pull/163


> It's not crucial but backporting can be more straightforward with git cherry-pick

I have noticed that `main` removes `peerDependecies` altogether and already adds `0.32.0` to the test variants

**Comment by gurgunday** [comment]
Yeah but after another look, I think there's an issue with main — I overlooked the custom CI that was present and replaced it with the generic fastify/workflows CI, which will actually prevent the typebox tests from being run

I'll revert that

**Comment by gurgunday** [comment]
Can you pull from v4? It should be good now

**Comment by nickfla1** [comment]
Looks like everything's good now!

**Review by gurgunday — CHANGES_REQUESTED** [review]
Actually, let's wait until we merge the CI fix on main, merge this there as well, and backport

This will ensure the upcoming v5 will also have v0.33 support

Sorry for the delay

**Comment by gurgunday** [comment]
Alright, so the CI is fixed on main, can you target it now with the same changes?

**Comment by nickfla1** [comment]
Updated!

**Review by gurgunday — APPROVED** [review]

**Pull request merged**
