### PR TITLE
fix: allow assigning provider-enabled instances to `FastifyInstance`

### PR DESCRIPTION
**Pull request by driimus**
#### Checklist

- [x] run `npm run test` and `npm run benchmark`
- [x] tests and/or benchmarks are included
- [x] documentation is changed or added - as guide in fastify/fastify#4371
- [x] commit message and code follows the [Developer's Certification of Origin](https://github.com/fastify/.github/blob/master/CONTRIBUTING.md#developers-certificate-of-origin-11)
      and the [Code of conduct](https://github.com/fastify/.github/blob/master/CODE_OF_CONDUCT.md)

Fix for fastify/fastify#4342 specific to this type provider.

### CODE REVIEW

**Review by zrosenbauer — APPROVED** [review]

**Comment by sinclairzx81** [comment]
@RafaelGSS Hi, just noticed this PR was still pending. 

I think it should be ok to merge this one through as the type specs were updated on https://github.com/fastify/fastify/pull/4371 in preparation for this. The original PR provided adequate testing when infering `unknown` for unresolvable types (currently the providers infer as `never`). So this PR would be the subsequent downstream update inline with the main project specs (see [here](https://github.com/fastify/fastify/pull/4371/files#diff-d4206b179610848a7f78ad3b7564a52422bc0a7dcf15fb37b33701a5f827b628R71))

> There's also a similar PR ready to go through for https://github.com/fastify/fastify-type-provider-json-schema-to-ts/pull/21 package which implements the same update as this provider.

So just as a quick reminder on this. This update relates specifically to enabling contravariance of the FastifyInstance when configured with a Type Provider. This should help greatly improve type composability and assignment of FastifyInstance (as it makes the configured provider instance assignable to non configured instances, which is awesome)

I don't anticipate this change causing any problems in existing codebases currently using this or the json-schema provider. But may want to use a minor revision just in case. 

Would be a great to see this PR merged through!

**Comment by RafaelGSS** [comment]
@driimus can you rebase?

**Comment by driimus** [comment]
@RafaelGSS the PR is already up-to-date with `main`. Happy to rebase onto another ref if you have one in mind.

If it's about the [failing CI for node14/windows](https://github.com/fastify/fastify-type-provider-typebox/actions/runs/3316098909/jobs/5803918529#step:4:1), that shouldn't be related to the changes in this PR. 

It sounds more like tapjs/node-tap#843. The project doesn't have a lockfile so the version of tap that gets installed is newer than the one in `package.json`:

https://github.com/fastify/fastify-type-provider-typebox/blob/cbd027e453b399cb15860121271fee76d42816a9/package.json#L46

**Review by RafaelGSS — APPROVED** [review]
LGTM.

**Comment by RafaelGSS** [comment]
I think the most appropriate is to release the minor when the tap issue is resolved.

**Pull request merged**
