### PR TITLE
feat: fastify 5 with separated type-providers

### PR DESCRIPTION
**Pull request by Bram-dc**
#### Checklist

- [ ] run `npm run test` and `npm run benchmark`
- [ ] tests and/or benchmarks are included
- [ ] documentation is changed or added
- [x] commit message and code follows the [Developer's Certification of Origin](https://github.com/fastify/.github/blob/master/CONTRIBUTING.md#developers-certificate-of-origin-11)
      and the [Code of conduct](https://github.com/fastify/.github/blob/master/CODE_OF_CONDUCT.md)

The tests will not work since this fastify 5 change has not been committed yet.

This is a patch to work correctly with https://github.com/fastify/fastify/pull/5427

### CODE REVIEW

**Comment by gurgunday** [comment]
Yeah so this PR might need to be combined with, or merged after, #137 (for tests and dependencies)

Feel free to take over that as well or I can look into it tonight

**Comment by gurgunday** [comment]
Please pull from the next branch

**Comment by Bram-dc** [comment]
Why is this PR closed? These type definition changes are approved and will break this project.

**Comment by jsumners** [comment]
The target branch got merged and deleted. So GitHub closed it automatically.

**Comment by Bram-dc** [comment]
Alright, I think the tests should run now!

**Review by mcollina — APPROVED** [review]
lgtm

**Pull request merged**
